Source/Web/NopCommerce/Presentation/Nop.Web/Administration/Controllers/CountryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using Nop.Admin.Extensions;
using Nop.Admin.Models.Directory;
using Nop.Core;
using Nop.Core.Domain.Directory;
using Nop.Services.Common;
using Nop.Services.Directory;
using Nop.Services.ExportImport;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Security;
using Nop.Services.Stores;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Kendoui;
using Nop.Web.Framework.Mvc;

namespace Nop.Admin.Controllers
{
    public partial class CountryController : BaseAdminController
	{
		#region Fields

        private readonly ICountryService _countryService;
        private readonly IStateProvinceService _stateProvinceService;
        private readonly ILocalizationService _localizationService;
	    private readonly IAddressService _addressService;
        private readonly IPermissionService _permissionService;
	    private readonly ILocalizedEntityService _localizedEntityService;
        private readonly ILanguageService _languageService;
        private readonly IStoreService _storeService;
        private readonly IStoreMappingService _storeMappingService;
        private readonly IExportManager _exportManager;
        private readonly IImportManager _importManager;
        private readonly ICustomerActivityService _customerActivityService;

        #endregion

        #region Constructors

        public CountryController(ICountryService countryService,
            IStateProvinceService stateProvinceService, 
            ILocalizationService localizationService,
            IAddressService addressService, 
            IPermissionService permissionService,
            ILocalizedEntityService localizedEntityService, 
            ILanguageService languageService,
            IStoreService storeService,
            IStoreMappingService storeMappingService,
            IExportManager exportManager,
            IImportManager importManager,
            ICustomerActivityService customerActivityService)
        {
            this._countryService = countryService;
            this._stateProvinceService = stateProvinceService;
            this._localizationService = localizationService;
            this._addressService = addressService;
            this._permissionService = permissionService;
            this._localizedEntityService = localizedEntityService;
            this._languageService = languageService;
            this._storeService = storeService;
            this._storeMappingService = storeMappingService;
            this._exportManager = exportManager;
            this._importManager = importManager;
            this._customerActivityService = customerActivityService;
        }

		#endregion 

        #region Utilities
        
        [NonAction]
        protected virtual void UpdateLocales(Country country, CountryModel model)
        {
            foreach (var localized in model.Locales)
            {
                _localizedEntityService.SaveLocalizedValue(country,
                                                               x => x.Name,
                                                               localized.Name,
                                                               localized.LanguageId);
            }
        }

        [NonAction]
        protected virtual void UpdateLocales(StateProvince stateProvince, StateProvinceModel model)
        {
            foreach (var localized in model.Locales)
            {
                _localizedEntityService.SaveLocalizedValue(stateProvince,
                                                               x => x.Name,
                                                               localized.Name,
                                                               localized.LanguageId);
            }
        }

        [NonAction]
        protected virtual void PrepareStoresMappingModel(CountryModel model, Country country, bool excludeProperties)
        {
            if (model == null)
                throw new ArgumentNullException("model");

            if (!excludeProperties && country != null)
                model.SelectedStoreIds = _storeMappingService.GetStoresIdsWithAccess(country).ToList();

            var allStores = _storeService.GetAllStores();
            foreach (var store in allStores)
            {
                model.AvailableStores.Add(new SelectListItem
                {
                    Text = store.Name,
                    Value = store.Id.ToString(),
                    Selected = model.SelectedStoreIds.Contains(store.Id)
                });
            }
        }

        [NonAction]
        protected virtual void SaveStoreMappings(Country country, CountryModel model)
        {
            country.LimitedToStores = model.SelectedStoreIds.Any();

            var existingStoreMappings = _storeMappingService.GetStoreMappings(country);
            var allStores = _storeService.GetAllStores();
            foreach (var store in allStores)
            {
                if (model.SelectedStoreIds.Contains(store.Id))
                {
                    //new store
                    if (existingStoreMappings.Count(sm => sm.StoreId == store.Id) == 0)
                        _storeMappingService.InsertStoreMapping(country, store.Id);
                }
                else
                {
                    //remove store
                    var storeMappingToDelete = existingStoreMappings.FirstOrDefault(sm => sm.StoreId == store.Id);
                    if (storeMappingToDelete != null)
                        _storeMappingService.DeleteStoreMapping(storeMappingToDelete);
                }
            }
        }

        #endregion

        #region Countries

        public virtual ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public virtual ActionResult List()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageCountries))
                return AccessDeniedView();

            return View();
        }

        [HttpPost]
        public virtual ActionResult CountryList(DataSourceRequest command)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageCountries))
                return AccessDeniedKendoGridJson();

            var countries = _countryService.GetAllCountries(showHidden: true);
            var gridModel = new DataSourceResult
            {
                Data = countries.Select(x => x.ToModel()),
                Total = countries.Count
            };

            return Json(gridModel);
        }
        
        public virtual ActionResult Create()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageCountries))
                return AccessDeniedView();

            var model = new CountryModel();
            //locales
            AddLocales(_languageService, model.Locales);
            //Stores
            PrepareStoresMappingModel(model, null, false);
            //default values
            model.Published = true;
            model.AllowsBilling = true;
            model.AllowsShipping = true;
            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        public virtual ActionResult Create(CountryModel model, bool continueEditing)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageCountries))
                return AccessDeniedView();

            if (ModelState.IsValid)
            {
                var country = model.ToEntity();
                _countryService.InsertCountry(country);

                //activity log
                _customerActivityService.InsertActivity("AddNewCountry", _localizationService.GetResource("ActivityLog.AddNewCountry"), country.Id);

                //locales
                UpdateLocales(country, model);
                //Stores
                SaveStoreMappings(country, model);

                SuccessNotification(_localizationService.GetResource("Admin.Configuration.Countries.Added"));

                if (continueEditing)
                {
                    //selected tab
                    SaveSelectedTabName();

                    return RedirectToAction("Edit", new { id = country.Id });
                }
                return RedirectToAction("List");
            }

            //If we got this far, something failed, redisplay form

            //Stores
            PrepareStoresMappingModel(model, null, true);
            return View(model);
        }

        public virtual ActionResult Edit(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageCountries))
                return AccessDeniedView();

            var country = _countryService.GetCountryById(id);
            if (country == null)
                //No country found with the specified id
                return RedirectToAction("List");

            var model = country.ToModel();
            //locales
            AddLocales(_languageService, model.Locales, (locale, languageId) =>
            {
                locale.Name = country.GetLocalized(x => x.Name, languageId, false, false);
            });
            //Stores
            PrepareStoresMappingModel(model, country, false);
            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        public virtual ActionResult Edit(CountryModel model, bool continueEditing)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageCountries))
                return AccessDeniedView();

            var country = _countryService.GetCountryById(model.Id);
            if (country == null)
                //No country found with the specified id
                return RedirectToAction("List");

            if (ModelState.IsValid)

Source/Web/NopCommerce/Presentation/Nop.Web/Administration/Controllers/DownloadController.cs
using System;
using System.IO;
using System.Web;
using System.Web.Mvc;
using Nop.Core;
using Nop.Core.Domain.Media;
using Nop.Services.Media;
using Nop.Web.Framework.Security;

namespace Nop.Admin.Controllers
{
    public partial class DownloadController : BaseAdminController
    {
        private readonly IDownloadService _downloadService;

        public DownloadController(IDownloadService downloadService)
        {
            this._downloadService = downloadService;
        }

        public virtual ActionResult DownloadFile(Guid downloadGuid)
        {
            var download = _downloadService.GetDownloadByGuid(downloadGuid);
            if (download == null)
                return Content("No download record found with the specified id");

            if (download.UseDownloadUrl)
                return new RedirectResult(download.DownloadUrl);

            //use stored data
            if (download.DownloadBinary == null)
                return Content(string.Format("Download data is not available any more. Download GD={0}", download.Id));

            string fileName = !String.IsNullOrWhiteSpace(download.Filename) ? download.Filename : download.Id.ToString();
            string contentType = !String.IsNullOrWhiteSpace(download.ContentType)
                ? download.ContentType
                : MimeTypes.ApplicationOctetStream;
            return new FileContentResult(download.DownloadBinary, contentType)
            {
                FileDownloadName = fileName + download.Extension
            };
        }

        [HttpPost]
        [ValidateInput(false)]
        //do not validate request token (XSRF)
        [AdminAntiForgery(true)] 
        public virtual ActionResult SaveDownloadUrl(string downloadUrl)
        {
            //insert
            var download = new Download
            {
                DownloadGuid = Guid.NewGuid(),
                UseDownloadUrl = true,
                DownloadUrl = downloadUrl,
                IsNew = true
              };
            _downloadService.InsertDownload(download);

            return Json(new { downloadId = download.Id }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        //do not validate request token (XSRF)
        [AdminAntiForgery(true)]
        public virtual ActionResult AsyncUpload()
        {
            //we process it distinct ways based on a browser
            //find more info here http://stackoverflow.com/questions/4884920/mvc3-valums-ajax-file-upload
            Stream stream = null;
            var fileName = "";
            var contentType = "";
            if (String.IsNullOrEmpty(Request["qqfile"]))
            {
                // IE
                HttpPostedFileBase httpPostedFile = Request.Files[0];
                if (httpPostedFile == null)
                    throw new ArgumentException("No file uploaded");
                stream = httpPostedFile.InputStream;
                fileName = Path.GetFileName(httpPostedFile.FileName);
                contentType = httpPostedFile.ContentType;
            }
            else
            {
                //Webkit, Mozilla
                stream = Request.InputStream;
                fileName = Request["qqfile"];
            }

            var fileBinary = new byte[stream.Length];
            stream.Read(fileBinary, 0, fileBinary.Length);

            var fileExtension = Path.GetExtension(fileName);
            if (!String.IsNullOrEmpty(fileExtension))
                fileExtension = fileExtension.ToLowerInvariant();

            var download = new Download
            {
                DownloadGuid = Guid.NewGuid(),
                UseDownloadUrl = false,
                DownloadUrl = "",
                DownloadBinary = fileBinary,
                ContentType = contentType,
                //we store filename without extension for downloads
                Filename = Path.GetFileNameWithoutExtension(fileName),
                Extension = fileExtension,
                IsNew = true
            };
            _downloadService.InsertDownload(download);

            //when returning JSON the mime-type must be set to text/plain
            //otherwise some browsers will pop-up a "Save As" dialog.
            return Json(new { success = true, 
                downloadId = download.Id, 
                downloadUrl = Url.Action("DownloadFile", new { downloadGuid= download.DownloadGuid }) },
                MimeTypes.TextPlain);
        }
    }
}

Source/Web/NopCommerce/Presentation/Nop.Web/Administration/Views/Shared/EditorTemplates/Address.cshtml
@model AddressModel

@if (Model.CountryEnabled && Model.StateProvinceEnabled)
{
    <script type="text/javascript">
        $(document).ready(function () {
            $("#@Html.FieldIdFor(model => model.CountryId)").change(function () {
                var selectedItem = $(this).val();
                var ddlStates = $("#@Html.FieldIdFor(model => model.StateProvinceId)");
                $.ajax({
                    cache: false,
                    type: "GET",
                    url: "@(Url.Action("GetStatesByCountryId", "Country"))",
                    data: { "countryId": selectedItem, "addSelectStateItem": "false" },
                    success: function (data) {
                        ddlStates.html('');
                        $.each(data, function (id, option) {
                            ddlStates.append($('<option></option>').val(option.id).html(option.name));
                        });
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert('Failed to retrieve states.');
                    }
                });
            });
        });
    </script>
}

@Html.HiddenFor(model => model.Id)
@Html.HiddenFor(model => model.FirstNameEnabled)
@Html.HiddenFor(model => model.FirstNameRequired)
@Html.HiddenFor(model => model.LastNameEnabled)
@Html.HiddenFor(model => model.LastNameRequired)
@Html.HiddenFor(model => model.EmailEnabled)
@Html.HiddenFor(model => model.EmailRequired)
@Html.HiddenFor(model => model.CompanyEnabled)
@Html.HiddenFor(model => model.CompanyRequired)
@Html.HiddenFor(model => model.CountryEnabled)
@Html.HiddenFor(model => model.CountryRequired)
@Html.HiddenFor(model => model.StateProvinceEnabled)
@Html.HiddenFor(model => model.CityEnabled)
@Html.HiddenFor(model => model.CityRequired)
@Html.HiddenFor(model => model.StreetAddressEnabled)
@Html.HiddenFor(model => model.StreetAddressRequired)
@Html.HiddenFor(model => model.StreetAddress2Enabled)
@Html.HiddenFor(model => model.StreetAddress2Required)
@Html.HiddenFor(model => model.ZipPostalCodeEnabled)
@Html.HiddenFor(model => model.ZipPostalCodeRequired)
@Html.HiddenFor(model => model.PhoneEnabled)
@Html.HiddenFor(model => model.PhoneRequired)
@Html.HiddenFor(model => model.FaxEnabled)
@Html.HiddenFor(model => model.FaxRequired)

@if (Model.FirstNameEnabled)
{
    <div class="form-group">
        <div class="col-md-3">
            @Html.NopLabelFor(model => model.FirstName)
        </div>
        <div class="col-md-9">
            @Html.NopEditorFor(model => model.FirstName, required: Model.FirstNameRequired)
            @Html.ValidationMessageFor(model => model.FirstName)
        </div>
    </div>
}
@if (Model.LastNameEnabled)
{
    <div class="form-group">
        <div class="col-md-3">
            @Html.NopLabelFor(model => model.LastName)
        </div>
        <div class="col-md-9">
            @Html.NopEditorFor(model => model.LastName, required: Model.LastNameRequired)
            @Html.ValidationMessageFor(model => model.LastName)
        </div>
    </div>
}
@if (Model.EmailEnabled)
{
    <div class="form-group">
        <div class="col-md-3">
            @Html.NopLabelFor(model => model.Email)
        </div>
        <div class="col-md-9">
            @Html.NopEditorFor(model => model.Email, required: Model.EmailRequired)
            @Html.ValidationMessageFor(model => model.Email)
        </div>
    </div>
}
@if (Model.CompanyEnabled)
{
    <div class="form-group">
        <div class="col-md-3">
            @Html.NopLabelFor(model => model.Company)
        </div>
        <div class="col-md-9">
            @Html.NopEditorFor(model => model.Company, required: Model.CompanyRequired)
            @Html.ValidationMessageFor(model => model.Company)
        </div>
    </div>
}
@if (Model.CountryEnabled)
{
    <div class="form-group">
        <div class="col-md-3">
            @Html.NopLabelFor(model => model.CountryId)
        </div>
        <div class="col-md-9">
            @Html.NopDropDownListFor(model => model.CountryId, Model.AvailableCountries, required: Model.CountryRequired)
            @Html.ValidationMessageFor(model => model.CountryId)
        </div>
    </div>
}
@if (Model.CountryEnabled && Model.StateProvinceEnabled)
{
    <div class="form-group">
        <div class="col-md-3">
            @Html.NopLabelFor(model => model.StateProvinceId)
        </div>
        <div class="col-md-9">
            @Html.NopDropDownListFor(model => model.StateProvinceId, Model.AvailableStates)
            @Html.ValidationMessageFor(model => model.StateProvinceId)
        </div>
    </div>
}
@if (Model.CityEnabled)
{
    <div class="form-group">
        <div class="col-md-3">
            @Html.NopLabelFor(model => model.City)
        </div>
        <div class="col-md-9">
            @Html.NopEditorFor(model => model.City, required: Model.CityRequired)
            @Html.ValidationMessageFor(model => model.City)
        </div>
    </div>
}
@if (Model.StreetAddressEnabled)
{
    <div class="form-group">
        <div class="col-md-3">
            @Html.NopLabelFor(model => model.Address1)
        </div>
        <div class="col-md-9">
            @Html.NopEditorFor(model => model.Address1, required: Model.StreetAddressRequired)
            @Html.ValidationMessageFor(model => model.Address1)
        </div>
    </div>
}
@if (Model.StreetAddress2Enabled)
{
    <div class="form-group">
        <div class="col-md-3">
            @Html.NopLabelFor(model => model.Address2)
        </div>
        <div class="col-md-9">
            @Html.NopEditorFor(model => model.Address2, required: Model.StreetAddress2Required)
            @Html.ValidationMessageFor(model => model.Address2)
        </div>
    </div>
}
@if (Model.ZipPostalCodeEnabled)
{
    <div class="form-group">
        <div class="col-md-3">
            @Html.NopLabelFor(model => model.ZipPostalCode)
        </div>
        <div class="col-md-9">
            @Html.NopEditorFor(model => model.ZipPostalCode, required: Model.ZipPostalCodeRequired)
            @Html.ValidationMessageFor(model => model.ZipPostalCode)
        </div>
    </div>
}
@if (Model.PhoneEnabled)
{
    <div class="form-group">
        <div class="col-md-3">
            @Html.NopLabelFor(model => model.PhoneNumber)
        </div>
        <div class="col-md-9">
            @Html.NopEditorFor(model => model.PhoneNumber, required: Model.PhoneRequired)
            @Html.ValidationMessageFor(model => model.PhoneNumber)
        </div>
    </div>
}
@if (Model.FaxEnabled)
{
    <div class="form-group">
        <div class="col-md-3">
            @Html.NopLabelFor(model => model.FaxNumber)
        </div>
        <div class="col-md-9">
            @Html.NopEditorFor(model => model.FaxNumber, required: Model.FaxRequired)
            @Html.ValidationMessageFor(model => model.FaxNumber)
        </div>
    </div>
}
@if (Model.CustomAddressAttributes.Count > 0)
{
    @Html.Partial("_AddressAttributes", Model.CustomAddressAttributes)
}

Source/Web/NopCommerce/Presentation/Nop.Web/Administration/Views/Shared/EditorTemplates/Download.cshtml
@model int

@using Nop.Core;
@using Nop.Web.Framework.UI;

@{
    //register CSS and JS
    Html.AddCssFileParts("~/Administration/Scripts/fineuploader/fineuploader-4.2.2.min.css");
    Html.AddScriptParts("~/Administration/Scripts/fineuploader/jquery.fineuploader-4.2.2.min.js");

    //other variables
    var randomNumber = CommonHelper.GenerateRandomInteger();
    var clientId = "download" + randomNumber;
    var downloadService = EngineContext.Current.Resolve<Nop.Services.Media.IDownloadService>();
    var download = downloadService.GetDownloadById(Model);

    var disableUrl = Convert.ToBoolean(ViewData["nop.DownloadEditor.DisableUrl"] ?? false);
}

<script type="text/javascript">
    $(document).ready(function () {
        $('#cbUseDownloadURL@(randomNumber)').click(toggleDownloadRecordType@(randomNumber));

        $('#saveDownloadUrl@(randomNumber)').click(function () {
            var downloadUrl = $("#downloadurl@(randomNumber)").val();
            $('#saveDownloadUrl@(randomNumber)').attr('disabled', true);
            $.ajax({
                cache: false,
                type: "POST",
                url: "@(Url.Action("SaveDownloadUrl", "Download", new { area = "Admin" }))",
                data: { "downloadUrl": downloadUrl },
                success: function (data) {
                    $('#pnlDownloadURLResult@(randomNumber)').fadeIn("slow").delay(1000).fadeOut("slow");
                    $("#@(clientId + "value") input").val(data.downloadId);
                    $('#saveDownloadUrl@(randomNumber)').attr('disabled', false);

                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert('Failed to save download object.');
                    $('#saveDownloadUrl@(randomNumber)').attr('disabled', false);
                }
            });
        });

        toggleDownloadRecordType@(randomNumber)();
    });

    function toggleDownloadRecordType@(randomNumber)() {
        if ($('#cbUseDownloadURL@(randomNumber)').is(':checked')) {
            $('#pnlDownloadURL@(randomNumber)').show();
            $('#pnlDownloadFile@(randomNumber)').hide();
        } else {
            $('#pnlDownloadURL@(randomNumber)').hide();
            $('#pnlDownloadFile@(randomNumber)').show();
        }
    }

</script>

<div id="@(clientId + "value")">
    @Html.HiddenFor(x => x)
</div>

<div class="panel panel-default">
    <div class="panel-body">
        @if (!disableUrl)
        {
            <div class="form-group">
                <div class="col-xs-4">
                    <div class="label-wrapper">
                        <label class="control-label">
                            @T("Admin.Download.UseDownloadURL")
                        </label>
                    </div>
                </div>
                <div class="col-xs-8">
                    <input type="checkbox" name="cbUseDownloadURL@(randomNumber)" id="cbUseDownloadURL@(randomNumber)"
                           @if (download != null && download.UseDownloadUrl) { <text> checked="checked" </text>        } />
                </div>
            </div>
        }
        <div id="pnlDownloadURL@(randomNumber)">
            <div class="form-group">
                <div class="col-xs-4">
                    <div class="label-wrapper">
                        <label class="control-label">
                            @T("Admin.Download.DownloadURL")
                        </label>
                    </div>
                </div>
                <div class="col-xs-8">
                    <input type="text" class="form-control" name="downloadurl@(randomNumber)" id="downloadurl@(randomNumber)"
                           @if (download != null && !String.IsNullOrEmpty(download.DownloadUrl)) { <text> value="@(download.DownloadUrl)" </text>  } />
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-8 col-xs-offset-4">
                    <button type="button" id="saveDownloadUrl@(randomNumber)" class="btn btn-primary">@T("Admin.Download.SaveDownloadURL")</button>
                    <div id="pnlDownloadURLResult@(randomNumber)" style="display: none;">@T("Admin.Download.DownloadURLSaved")</div>
                </div>
            </div>
        </div>
        <div class="form-group" id="pnlDownloadFile@(randomNumber)">
            <div class="col-xs-4">
                <div class="label-wrapper">
                    <label class="control-label">
                        @T("Admin.Download.UploadFile")
                    </label>
                </div>
            </div>
            <div class="col-xs-8">
                @*fine uploader container*@
                <div id="@clientId">
                    <noscript>
                        <p>
                            Please enable JavaScript to use file uploader.
                        </p>
                        <!-- or put a simple form for upload here -->
                    </noscript>
                </div>
                @*fine uploader template (keep it synchronized to \Content\fineuploader\templates\default.html)*@
                <script type="text/template" id="@(clientId)-qq-template">
                    <div class="qq-uploader-selector qq-uploader">
                        <div class="qq-upload-drop-area-selector qq-upload-drop-area" qq-hide-dropzone>
                            <span>@T("Common.FileUploader.DropFiles")</span>
                        </div>
                        <div class="qq-upload-button-selector qq-upload-button">
                            <div>@T("Common.FileUploader.Upload")</div>
                        </div>
                        <span class="qq-drop-processing-selector qq-drop-processing">
                            <span>@T("Common.FileUploader.Processing")</span>
                            <span class="qq-drop-processing-spinner-selector qq-drop-processing-spinner"></span>
                        </span>
                        <ul class="qq-upload-list-selector qq-upload-list">
                            <li>
                                <div class="qq-progress-bar-container-selector">
                                    <div class="qq-progress-bar-selector qq-progress-bar"></div>
                                </div>
                                <span class="qq-upload-spinner-selector qq-upload-spinner"></span>
                                <span class="qq-edit-filename-icon-selector qq-edit-filename-icon"></span>
                                <span class="qq-upload-file-selector qq-upload-file"></span>
                                <input class="qq-edit-filename-selector qq-edit-filename" tabindex="0" type="text">
                                <span class="qq-upload-size-selector qq-upload-size"></span>
                                <a class="qq-upload-cancel-selector qq-upload-cancel" href="#">@T("Common.FileUploader.Cancel")</a>
                                <a class="qq-upload-retry-selector qq-upload-retry" href="#">@T("Common.FileUploader.Retry")</a>
                                <a class="qq-upload-delete-selector qq-upload-delete" href="#">@T("Common.FileUploader.Delete")</a>
                                <span class="qq-upload-status-text-selector qq-upload-status-text"></span>
                            </li>
                        </ul>
                    </div>
                </script>

                <script type="text/javascript">

                    $(document).ready(function () {
                        $("#@clientId").fineUploader({
                            request: {
                                endpoint: '@(Url.Action("AsyncUpload", "Download", new { area = "Admin" }))'
                            },
                            template: "@(clientId)-qq-template",
                            multiple: false
                        }).on("complete", function (event, id, name, responseJSON, xhr) {
                            $("#@(clientId + "downloadurl")").html("<a class='btn btn-default margin-t-5' href='" + responseJSON.downloadUrl + "'><i class='fa fa-download'></i>@T("Admin.Download.DownloadUploadedFile")</a>");
                            $("#@(clientId + "value") input").val(responseJSON.downloadId);
                            $("#@(clientId + "remove")").show();
                        });


                        $("#@(clientId + "remove")").click(function (e) {
                            $("#@(clientId + "downloadurl")").html("");
                            $("#@(clientId + "value") input").val(0);
                            $(this).hide();
                        });
                    });

                </script>
                <div style="clear: both;">
                    <div id="@(clientId + "downloadurl")" class="pull-left margin-r-5">
                        @if (download != null)
                        {
                            <a class='btn btn-default margin-t-5' href="@(Url.Action("DownloadFile", "Download", new { downloadGuid = download.DownloadGuid, area = "Admin" }))"><i class='fa fa-download'></i>@T("Admin.Download.DownloadUploadedFile")</a>
                        }
                    </div>
                    <div class="pull-left">
                        @if (download != null)
                        {
                            <span id="@(clientId + "remove")" class="btn btn-default margin-t-5"><i class="fa fa-trash"></i>@T("Admin.Download.RemoveDownload")</span>
                        }
                        else
                        {
                            <span id="@(clientId + "remove")" class="btn btn-default margin-t-5" style="display:none;"><i class="fa fa-trash"></i>@T("Admin.Download.RemoveDownload")</span>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>